### ISSUE TITLE
Can't send requests, or get a response

### ISSUE THREAD

**Issue by it-s** [dridk/cuterest#1]
Every time I try to send a request I receive nothing. But common line shows this:
set URL  QUrl( "https://api.linkedin.com/v1/people/id=xxx" ) 
send request  QUrl( "https://api.linkedin.com/v1/people/id=xxx" ) 
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
QSslSocket: cannot call unresolved function ERR_get_error

**Comment by dridk** [comment]
On Mac ? 
You may have to install openssl..  Don't know ! 
Anyway, try this api request : http://api.duckduckgo.com/?q=apple&format=json&pretty=1 
It's json and http !

**Comment by it-s** [comment]
Does the app handle https requests?
