### ISSUE TITLE
JSON dada is not parsed

### ISSUE THREAD

**Issue by it-s** [dridk/cuterest#12]
# Steps to reproduce:
* Install node.js
* Install https://github.com/typicode/json-server
* Setup simple JSON file:
sample.json
```json
{
  "users": [
    {
      "id": 1,
      "name": "Joe",
      "email": "joe@places.com"
    },
    {
      "id": 2,
      "name": "Joe2",
      "email": "joe@places.com"
    }
  ]
}
```
* Run service: json-server sample.json
* Start cureRest and navigate to http://localhost/users

## Expected result
JSON tab shows:
```json
    {
      "id": 1,
      "name": "Joe",
      "email": "joe@places.com"
    },
    {
      "id": 2,
      "name": "Joe2",
      "email": "joe@places.com"
    }
```
## Actual result
JSON tab is empty

**Comment by dridk** [comment]
Are you sure you have the right port ?

**Comment by it-s** [comment]
This has nothing to do with port. I get the data back. It's loaded properly, but JSON tab shows nothing. Every other tab shows the data right.

**Comment by dridk** [comment]
I think you nodejs return json with simple quote ? Right ?

**Comment by it-s** [comment]
"Simple quote"? What do you mean?
I used http://jsonlint.com/ service to validate my test JSON and it says my JSON is valid...

**Comment by it-s** [comment]
It seems Qt has issues parsing arrays! So, JSON objects, such as {"key"="value"} are parsed no problem; BUT JSON array [{"key"="value"},{"key"="value"}] result in error.

**Comment by dridk** [comment]
That's because Json Array cannot be as root.. It can ?

2015-02-25 16:44 GMT+01:00 Eugene Trounev <notifications@github.com>:

> It seems Qt has issues parsing arrays! So, JSON objects, such as
> {"key"="value"} are parsed no problem; BUT JSON array
> [{"key"="value"},{"key"="value"}] result in error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dridk/cuterest/issues/12#issuecomment-75983464>.
>



-- 
-- 
Sacha schutz
+33651571606
dridk.me
Fork me on github <https://github.com/>

**Comment by it-s** [comment]
Hmmm, maybe you are right.
