### ISSUE TITLE
Icons highlight to wthite

### ISSUE THREAD

**Issue by it-s** [dridk/cuterest#24]
Currently on Windows platform icons highlight to white when hovered, which makes them blend into the default grey background.

**Comment by dridk** [comment]
give me a color

**Comment by it-s** [comment]
NO, this is not how it works :P
I'm not a color vendor. The easiest solution would be to change element opacity on hover to 0.8, and back to 1 on blur. But you have to ask yourself "What will happen on Linux systems with dark color scheme?"
