### ISSUE TITLE
Pressing [-] in Custom Request causes ASSERT

### ISSUE THREAD

**Issue by it-s** [dridk/cuterest#25]
### Steps to reproduce
- Start application
- Click Custom Request button to the left of the URL entry box at the top
- Click [-] button under the Headers table in the Custom Request window

### Expected
The default "Content Type" entry should be removed from the list.
The [-] button should become inactive as the list is now empty.

### Actual result
Application terminates with following reason:
ASSERT: "first >= 0" in file itemmodels\qabstractitemmodel.cpp, line 2656

**Comment by it-s** [comment]
It seems that the problem is that no row is highlighted. Possible solution could be: if no row is selected the last could be selected automatically.

**Comment by dridk** [comment]
fixed
