### ISSUE TITLE
Can not compile under Windows

### ISSUE THREAD

**Issue by it-s** [dridk/cuterest#3]
When compiling under windows I get en error:
...\GitHub\build-CuteRest-Desktop_Qt_5_4_0_MinGW_32bit-Debug\debug\proxysettingswidget.o:-1: In function `ZN19ProxySettingsWidgetC2EP7QWidget':
...\GitHub\cuterest\proxysettingswidget.cpp:4: error: undefined reference to `vtable for ProxySettingsWidget'
Using Qt 4.5, with MinGW 32bit compiler

**Comment by dridk** [comment]
probably need a ; clean all ; qmake ; make all
